package za.co.trademesh.modules.document.domain;

public enum DocumentMismatchRule {
    DOCUMENT_QUANTITY_MISMATCH,
    DOCUMENT_PRICE_MISMATCH,
    DOCUMENT_SUPPLIER_MISMATCH,
    DOCUMENT_CUSTOMER_MISMATCH,
    DOCUMENT_DESTINATION_MISMATCH,
    DOCUMENT_DATE_MISMATCH,
    DUPLICATE_DOCUMENT_CONTENT
}
