import { makeStyles, tokens } from "@fluentui/react-components";

export const useAccessStyles = makeStyles({
    skipLink: {
        position: "absolute",
        left: "-999px",
        top: "0",
        zIndex: 2,
        minHeight: "44px",
        padding: tokens.spacingHorizontalM,
        backgroundColor: tokens.colorNeutralBackground1,
        color: tokens.colorNeutralForeground1,
        ":focus": {
            left: tokens.spacingHorizontalS,
            top: tokens.spacingVerticalS,
        },
    },
    shell: {
        minHeight: "100dvh",
        width: "100%",
        display: "flex",
        flexDirection: "column",
        backgroundColor: tokens.colorNeutralBackground3,
        boxSizing: "border-box",
    },
    header: {
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalM,
        padding: tokens.spacingHorizontalL,
        backgroundColor: tokens.colorNeutralBackground1,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    brand: {
        margin: 0,
        color: tokens.colorBrandForeground1,
        fontSize: tokens.fontSizeBase500,
        fontWeight: tokens.fontWeightSemibold,
    },
    nav: {
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
    },
    navLink: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "44px",
        minWidth: "44px",
        paddingLeft: tokens.spacingHorizontalM,
        paddingRight: tokens.spacingHorizontalM,
        color: tokens.colorNeutralForeground1,
        textDecoration: "none",
        borderRadius: tokens.borderRadiusMedium,
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground3,
        },
        ":focus-visible": {
            outline: `2px solid ${tokens.colorStrokeFocus2}`,
            outlineOffset: "2px",
        },
    },
    navLinkActive: {
        backgroundColor: tokens.colorBrandBackground,
        color: tokens.colorNeutralForegroundOnBrand,
        fontWeight: tokens.fontWeightSemibold,
    },
    touchTarget: {
        minHeight: "44px",
        minWidth: "44px",
    },
    main: {
        flex: 1,
        width: "100%",
        maxWidth: "80rem",
        marginLeft: "auto",
        marginRight: "auto",
        padding: tokens.spacingHorizontalL,
        boxSizing: "border-box",
    },
    page: {
        minHeight: "100dvh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: tokens.spacingHorizontalL,
        backgroundColor: tokens.colorNeutralBackground3,
        boxSizing: "border-box",
    },
    card: {
        width: "100%",
        maxWidth: "28rem",
        borderTopWidth: "4px",
        borderTopStyle: "solid",
        borderTopColor: tokens.colorBrandBackground,
    },
    stack: {
        display: "flex",
        flexDirection: "column",
        rowGap: tokens.spacingVerticalM,
    },
    title: {
        marginTop: 0,
        marginBottom: 0,
    },
});
