trademesh:
  access:
    turnstile:
      provider: cloudflare
    otp:
      provider: twilio
  integrations:
    momo:
      provider: http
  delivery:
    search:
      speech-provider: google
      distance-provider: google
  notifications:
    mobile:
      provider: twilio
